# Generated by Django 3.2.2 on 2021-05-09 10:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_order', models.IntegerField()),
                ('rank', models.CharField(max_length=16)),
                ('name', models.TextField()),
                ('scores_overall', models.CharField(max_length=16)),
                ('scores_overall_rank', models.IntegerField()),
                ('scores_teaching', models.DecimalField(decimal_places=1, max_digits=4)),
                ('scores_teaching_rank', models.IntegerField()),
                ('scores_research', models.DecimalField(decimal_places=1, max_digits=4)),
                ('scores_research_rank', models.IntegerField()),
                ('scores_citations', models.DecimalField(decimal_places=1, max_digits=4)),
                ('scores_citations_rank', models.IntegerField()),
                ('scores_industry_income', models.DecimalField(decimal_places=1, max_digits=4)),
                ('scores_industry_income_rank', models.IntegerField()),
                ('scores_international_outlook', models.DecimalField(decimal_places=1, max_digits=4)),
                ('scores_international_outlook_rank', models.IntegerField()),
                ('slug', models.SlugField(default='not-found')),
                ('location', models.TextField()),
                ('stats_number_students', models.IntegerField()),
                ('stats_student_staff_ratio', models.DecimalField(decimal_places=1, max_digits=4)),
                ('stats_pc_intl_students', models.CharField(max_length=5)),
                ('stats_female_male_ratio', models.CharField(blank=True, max_length=16)),
                ('subjects_offered', models.TextField()),
                ('bookmarks', models.ManyToManyField(blank=True, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
